
const phonesData = [
    {
        id: 101,
        name: "Apple iPhone 15 Pro Max 256GB",
        main_category: "smartphones",
        sub_category: "apple",
        image_url: "images/apple/15promax.jpg",
        rating: 4.8,
        actual_price: 129990,
        discount_price: 124990,
        created_at: "2024-01-15T10:30:00",
        brand: "apple",
        storage: "256GB",
        color: "Титан",
        os: "iOS 17"
    },
    {
        id: 102,
        name: "Samsung Galaxy S24 Ultra 512GB",
        main_category: "smartphones",
        sub_category: "samsung",
        image_url: "images/samsung/s24ultra.jpg",
        rating: 4.7,
        actual_price: 109990,
        discount_price: 104990,
        created_at: "2024-01-10T14:20:00",
        brand: "samsung",
        storage: "512GB",
        color: "Черный",
        os: "Android 14"
    },
    {
        id: 103,
        name: "Xiaomi 14 Pro 256GB",
        main_category: "smartphones",
        sub_category: "xiaomi",
        image_url: "images/xiaomi/14pro.jpg",
        rating: 4.6,
        actual_price: 79990,
        discount_price: null,
        created_at: "2024-01-05T09:15:00",
        brand: "xiaomi",
        storage: "256GB",
        color: "Зеленый",
        os: "Android 14"
    },
    {
        id: 104,
        name: "Google Pixel 8 Pro 256GB",
        main_category: "smartphones",
        sub_category: "google",
        image_url: "images/google/8pro.jpg",
        rating: 4.5,
        actual_price: 89990,
        discount_price: 84990,
        created_at: "2024-01-12T11:45:00",
        brand: "google",
        storage: "256GB",
        color: "Белый",
        os: "Android 14"
    },
    {
        id: 105,
        name: "Huawei P60 Pro 512GB",
        main_category: "smartphones",
        sub_category: "huawei",
        image_url: "images/huawei/p60pro.jpg",
        rating: 4.4,
        actual_price: 84990,
        discount_price: 79990,
        created_at: "2024-01-08T16:30:00",
        brand: "huawei",
        storage: "512GB",
        color: "Золотой",
        os: "HarmonyOS"
    },
    {
        id: 106,
        name: "Apple iPhone 14 128GB",
        main_category: "smartphones",
        sub_category: "apple",
        image_url: "images/apple/14purple.jpg",
        rating: 4.5,
        actual_price: 74990,
        discount_price: 69990,
        created_at: "2024-01-03T13:10:00",
        brand: "apple",
        storage: "128GB",
        color: "Фиолетовый",
        os: "iOS 16"
    },
    {
        id: 107,
        name: "Samsung Galaxy Z Fold5 256GB",
        main_category: "smartphones",
        sub_category: "samsung",
        image_url: "images/samsung/zfold5.jpg",
        rating: 4.6,
        actual_price: 149990,
        discount_price: null,
        created_at: "2024-01-14T10:00:00",
        brand: "samsung",
        storage: "256GB",
        color: "Бежевый",
        os: "Android 13"
    },
    {
        id: 108,
        name: "Xiaomi Redmi Note 13 Pro+",
        main_category: "smartphones",
        sub_category: "xiaomi",
        image_url: "images/xiaomi/13pro.jpg",
        rating: 4.3,
        actual_price: 34990,
        discount_price: 32990,
        created_at: "2024-01-07T15:20:00",
        brand: "xiaomi",
        storage: "256GB",
        color: "Черный",
        os: "Android 13"
    },
    {
        id: 109,
        name: "OnePlus 12 256GB",
        main_category: "smartphones",
        sub_category: "other",
        image_url: "images/other/oneplus12green.jpg",
        rating: 4.6,
        actual_price: 69990,
        discount_price: 64990,
        created_at: "2024-01-11T12:30:00",
        brand: "other",
        storage: "256GB",
        color: "Зеленый",
        os: "Android 14"
    },
    {
        id: 110,
        name: "Apple iPhone 16 2025 256GB",
        main_category: "smartphones",
        sub_category: "apple",
        image_url: "images/apple/16.jpg",
        rating: 4.2,
        actual_price: 44990,
        discount_price: 41990,
        created_at: "2025-01-09T14:45:00",
        brand: "apple",
        storage: "512GB",
        color: "Зеленый",
        os: "iOS 18"
    },
    {
        id: 111,
        name: "Samsung Galaxy A35 128GB",
        main_category: "smartphones",
        sub_category: "samsung",
        image_url: "images/samsung/a35.jpg",
        rating: 4.1,
        actual_price: 29990,
        discount_price: 27990,
        created_at: "2024-01-04T11:20:00",
        brand: "samsung",
        storage: "128GB",
        color: "Фиолетовый",
        os: "Android 13"
    },
    {
        id: 112,
        name: "Google Pixel 7a 128GB",
        main_category: "smartphones",
        sub_category: "google",
        image_url: "images/google/pixel7a.jpg",
        rating: 4.4,
        actual_price: 39990,
        discount_price: 36990,
        created_at: "2024-01-13T09:30:00",
        brand: "google",
        storage: "128GB",
        color: "Коралловый",
        os: "Android 13"
    },
    {
        id: 113,
        name: "Huawei Nova 11 256GB",
        main_category: "smartphones",
        sub_category: "huawei",
        image_url: "images/huawei/nova.jpg",
        rating: 4.0,
        actual_price: 32990,
        discount_price: 29990,
        created_at: "2024-01-06T17:15:00",
        brand: "huawei",
        storage: "256GB",
        color: "Розовый",
        os: "HarmonyOS"
    },
    {
        id: 114,
        name: "Apple iPhone 13 128GB",
        main_category: "smartphones",
        sub_category: "apple",
        image_url: "images/apple/13pink.jpg",
        rating: 4.3,
        actual_price: 54990,
        discount_price: 49990,
        created_at: "2024-01-02T10:50:00",
        brand: "apple",
        storage: "128GB",
        color: "Розовый",
        os: "iOS 15"
    },
    {
        id: 115,
        name: "Samsung Galaxy S23 256GB",
        main_category: "smartphones",
        sub_category: "samsung",
        image_url: "images/samsung/s23cream.jpg",
        rating: 4.5,
        actual_price: 69990,
        discount_price: 64990,
        created_at: "2024-01-01T08:30:00",
        brand: "samsung",
        storage: "256GB",
        color: "Кремовый",
        os: "Android 13"
    },
    {
        id: 116,
        name: "Xiaomi 13T Pro 512GB",
        main_category: "smartphones",
        sub_category: "xiaomi",
        image_url: "images/xiaomi/13.jpg",
        rating: 4.4,
        actual_price: 59990,
        discount_price: 55990,
        created_at: "2024-01-10T15:40:00",
        brand: "xiaomi",
        storage: "512GB",
        color: "Синий",
        os: "Android 13"
    },
    {
        id: 117,
        name: "Nothing Phone (2) 256GB",
        main_category: "smartphones",
        sub_category: "other",
        image_url: "images/other/nothingphone2.jpg",
        rating: 4.3,
        actual_price: 54990,
        discount_price: null,
        created_at: "2024-01-15T14:00:00",
        brand: "other",
        storage: "256GB",
        color: "Белый",
        os: "Android 13"
    },
    {
        id: 118,
        name: "Apple iPhone 15 Plus 128GB",
        main_category: "smartphones",
        sub_category: "apple",
        image_url: "images/apple/15plus.jpg",
        rating: 4.6,
        actual_price: 89990,
        discount_price: 86990,
        created_at: "2024-01-14T13:25:00",
        brand: "apple",
        storage: "128GB",
        color: "Золотой",
        os: "iOS 17"
    },
    {
        id: 119,
        name: "Samsung Galaxy Z Flip5 256GB",
        main_category: "smartphones",
        sub_category: "samsung",
        image_url: "images/samsung/zflip5.jpg",
        rating: 4.5,
        actual_price: 89990,
        discount_price: 84990,
        created_at: "2024-01-13T16:10:00",
        brand: "samsung",
        storage: "256GB",
        color: "Фиолетовый",
        os: "Android 13"
    },
    {
        id: 120,
        name: "Xiaomi Poco X6 Pro 256GB",
        main_category: "smartphones",
        sub_category: "xiaomi",
        image_url: "images/xiaomi/x6pro.jpg",
        rating: 4.2,
        actual_price: 27990,
        discount_price: 25990,
        created_at: "2024-01-08T12:15:00",
        brand: "xiaomi",
        storage: "256GB",
        color: "Желтый",
        os: "Android 13"
    },
    {
        id: 121,
        name: "Google Pixel Fold 256GB",
        main_category: "smartphones",
        sub_category: "google",
        image_url: "images/google/pixelfold.jpg",
        rating: 4.5,
        actual_price: 119990,
        discount_price: 114990,
        created_at: "2024-01-12T10:45:00",
        brand: "google",
        storage: "256GB",
        color: "Черный",
        os: "Android 13"
    },
    {
        id: 122,
        name: "Huawei Mate 50 Pro 256GB",
        main_category: "smartphones",
        sub_category: "huawei",
        image_url: "images/huawei/mate50.jpg",
        rating: 4.4,
        actual_price: 69990,
        discount_price: 64990,
        created_at: "2024-01-07T14:30:00",
        brand: "huawei",
        storage: "256GB",
        color: "Серебристый",
        os: "HarmonyOS"
    },
    {
        id: 123,
        name: "Apple iPhone 15 Blue 256GB",
        main_category: "smartphones",
        sub_category: "apple",
        image_url: "images/apple/15blue.jpg",
        rating: 4.0,
        actual_price: 42990,
        discount_price: 39990,
        created_at: "2024-01-05T11:10:00",
        brand: "apple",
        storage: "256GB",
        color: "Голубой",
        os: "iOS 18"
    },
    {
        id: 124,
        name: "Samsung Galaxy A34 128GB",
        main_category: "smartphones",
        sub_category: "samsung",
        image_url: "images/samsung/a34lime.jpg",
        rating: 4.0,
        actual_price: 24990,
        discount_price: 22990,
        created_at: "2024-01-09T15:20:00",
        brand: "samsung",
        storage: "128GB",
        color: "Лаймовый",
        os: "Android 13"
    },
    {
        id: 125,
        name: "Xiaomi Redmi 12 128GB",
        main_category: "smartphones",
        sub_category: "xiaomi",
        image_url: "images/xiaomi/12blue.jpg",
        rating: 3.9,
        actual_price: 14990,
        discount_price: 13990,
        created_at: "2024-01-03T09:40:00",
        brand: "xiaomi",
        storage: "128GB",
        color: "Голубой",
        os: "Android 12"
    },
    {
        id: 126,
        name: "Motorola Edge 40 256GB",
        main_category: "smartphones",
        sub_category: "other",
        image_url: "images/other/motorola40.jpg",
        rating: 4.1,
        actual_price: 34990,
        discount_price: 31990,
        created_at: "2024-01-11T13:50:00",
        brand: "other",
        storage: "256GB",
        color: "Черный",
        os: "Android 13"
    },
    {
        id: 127,
        name: "Apple iPhone 17 Pro Max 256GB",
        main_category: "smartphones",
        sub_category: "apple",
        image_url: "images/apple/17.jpg",
        rating: 4.5,
        actual_price: 79990,
        discount_price: 76990,
        created_at: "2024-01-13T10:25:00",
        brand: "apple",
        storage: "256GB",
        color: "Оранжевый",
        os: "iOS 26"
    },
    {
        id: 128,
        name: "Samsung Galaxy S23 FE 256GB",
        main_category: "smartphones",
        sub_category: "samsung",
        image_url: "images/samsung/s23fe.jpg",
        rating: 4.3,
        actual_price: 49990,
        discount_price: 46990,
        created_at: "2024-01-06T12:30:00",
        brand: "samsung",
        storage: "256GB",
        color: "Пурпурный",
        os: "Android 13"
    },
    {
        id: 129,
        name: "Xiaomi 13 Lite 256GB",
        main_category: "smartphones",
        sub_category: "xiaomi",
        image_url: "images/xiaomi/13lite.jpg",
        rating: 4.2,
        actual_price: 34990,
        discount_price: 32990,
        created_at: "2024-01-04T14:15:00",
        brand: "xiaomi",
        storage: "256GB",
        color: "Розовый",
        os: "Android 13"
    },
    {
        id: 130,
        name: "Google Pixel 7 128GB",
        main_category: "smartphones",
        sub_category: "google",
        image_url: "images/google/pixel7lemongrass.jpg",
        rating: 4.4,
        actual_price: 49990,
        discount_price: 45990,
        created_at: "2024-01-02T15:45:00",
        brand: "google",
        storage: "128GB",
        color: "Лимонный",
        os: "Android 13"
    }
];

